# Generated by Django 3.1.7 on 2021-04-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categoryName',
            field=models.CharField(default='无', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endId', models.IntegerField(blank=True, default=0, null=True)),
                ('startId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.user')),
            ],
            options={
                'db_table': 'userrelation',
                'managed': True,
            },
        ),
    ]
