# Generated by Django 3.1.7 on 2021-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210404_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrelation',
            old_name='endId',
            new_name='endid',
        ),
        migrations.RemoveField(
            model_name='userrelation',
            name='startId',
        ),
        migrations.AddField(
            model_name='userrelation',
            name='startid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
